### ISSUE TITLE
Version 4.2.0 import broken

### ISSUE THREAD

**Issue by loopingz** [RebeccaStevens/deepmerge-ts#145]
# Bug Report

When upgrading from 4.1.x to 4.2.0, same code do not compile anymore

```
error TS2307: Cannot find module 'deepmerge-ts' or its corresponding type declarations.

2 import { deepmerge } from "deepmerge-ts";
```

## Expected behavior

Normal compilation
